### PR TITLE
Ensure: Handle active replica max files

### PR DESCRIPTION
**Pull request by kpawar-sap**
The calls failed during promote replica calls are retriggred in manila-ensure e.g. update_volume_efficiency_attributes and set_volume_max_files for neo domain.

### CODE REVIEW

**Review by chuan137 — CHANGES_REQUESTED** [review]

**Comment by kpawar-sap** [comment]
updated this PR to consider only max_files. I will create separate PR efficiency_attributes. @chuan137  @Carthaca review.

**Comment by Carthaca** [comment]
I think we can close this, the max_files are already handled in https://github.com/sapcc/manila/blob/b91c339b2d125ccbd7560e7820326b17c656909d/manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py#L2670-L2679

**Comment by chuan137** [comment]
agree. we can close this for now. Max files are maintained by ensure, and for efficiency settings we are going to deal in different task.

**Comment by kpawar-sap** [comment]
ensure will check share type
from share type it will determine efficiency setting
for neo domain volumes, we have to apply our own logic

for neo domain check, we need to write domain name in the comment field of netapp backend volumes.

**Pull request closed without merging**
