### PR TITLE
sapcc: raise again on share from snap az mismatch

### PR DESCRIPTION
**Pull request by Carthaca**
error is no popping up, on the other hand not throwing the excpetion causes inconsistencies (shares reporting wrong AZ)

Change-Id: I562a4bfb3339b738c4d67f78166bbc3e1b3b0a11

undo https://github.com/sapcc/manila/commit/ed19c196df72a3bdac833364c8c8868765b7d542

### CODE REVIEW

**Comment by Carthaca** [comment]
unit test error looks unrelated - but how can that be? 🤔 I will have a look next week

```
manila.tests.share.drivers.cephfs.test_driver.NFSProtocolHelperTestCase.test_init_identify_local_host_1_fakeip
--------------------------------------------------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/tmp/build/ac3d517b/pull-request-manila/.tox/py3/lib/python3.8/site-packages/ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)

      File "/tmp/build/ac3d517b/pull-request-manila/manila/tests/share/drivers/cephfs/test_driver.py", line 981, in test_init_identify_local_host
    self.assertFalse(driver.LOG.info.called)

      File "/root/.pyenv/versions/3.8.11/lib/python3.8/unittest/case.py", line 759, in assertFalse
    raise self.failureException(msg)

    AssertionError: True is not false
```

**Comment by kpawar-sap** [comment]
py3 tests are failing. please fix to continue review.

**Comment by Carthaca** [comment]
I did a rerun of the tests, they are green now - please review

**Review by chuan137 — CHANGES_REQUESTED** [review]
thanks for working on this. A minor suggestion, can you please reuse `msg` while building `error_msg`. It took me a while to compare the two texts and then understood the differences.

**Review by chuan137 — APPROVED** [review]
LGTM

**Review by kpawar-sap — APPROVED** [review]

**Pull request merged**
