### PR TITLE
sapcc: try blocks for all promote additions

### PR DESCRIPTION
**Pull request by Carthaca**
There is no rollback. We don't want to come to the situation again, that we have an unfinished promote. It later got completely damaged by an attempted repair in the periodic `update_replica_state`.

Also we had a case, where we don't know why the
`if effi_opts['cross_dedup_disabled']` codepath was taken with an efficiency policy seemingly set to 'auto' (not 'inline-only') all the time. Add logging for more insights the next time.

Change-Id: Iaa02525f70e557d98b33dc9fb5ce8c6afa440118

### CODE REVIEW

**Comment by Carthaca** [comment]
Tested additional logging in qa:

```
2023-06-01 07:09:23,895 11 DEBUG manila.share.drivers.netapp.dataontap.cluster_mode.lib_base [req-XXX gNone userid projectid - - -] volume_efficiency_status of share 'share_27709334_ce9b_4393_9865_5f311afcb002'is '{'dedupe': True, 'compression': True, 'policy': 'auto', 'cross_dedup_disabled': False}' _get_efficiency_options /var/lib/openstack/lib/python3.8/site-packages/manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py:767
```

**Review by chuan137 — APPROVED** [review]
This allows promoting replica to log errors and continue to finish. The errors should be later manually fixed. Ok, as a quick fix

**Comment by Carthaca** [comment]
Yes, this means we have a follow-up task:

check if ensure would correct those errors, if not: create alerting

**Comment by chuan137** [comment]
>  check if ensure would correct those errors, if not: create alerting

what about retry during promotion before print out and carry on

**Pull request merged**
