### PR TITLE
simplify 'Delete queried ports from neutron during share server delete'

### PR DESCRIPTION
**Pull request by Carthaca**
followup to 72f01f143f7f532ab51ca7c3ec6fb0f4368746e6

share network is not used, it may even be already deleted

Change-Id: I84cc70064a33d790db519acdabcff29e74770f98

### CODE REVIEW

**Comment by kpawar-sap** [comment]
can you please not change the definition of function and instead handle share_network_not found exception ?

**Comment by Carthaca** [comment]
But upstream also isn't using the share_network variable. What is the use case for sending this share network data around if it is not used later?

Loading `share_net_subnet` makes sense, yes.

**Comment by kpawar-sap** [comment]
> But upstream also isn't using the share_network variable. What is the use case for sending this share network data around if it is not used later?
> 
> Loading `share_net_subnet` makes sense, yes.

share network was added to align with definition of allocate_network. Yes, its not used though.

**Review by kpawar-sap — APPROVED** [review]

**Review by chuan137 — APPROVED** [review]
lgtm

**Pull request merged**
