### PR TITLE
[NetApp] delete source ipspace after server migration completed

### PR DESCRIPTION
**Pull request by chuan137**
clean up ipspace/broadcast domain and vlan on source side

Change-Id: I23e8e0e890c146d325232d9e9a2aa8cf13b628e6

### CODE REVIEW

**Comment by chuan137** [comment]
vlan is not cleaned up, and netapp will move them to default ipspace. so I have proposed another fix #195, to create vserver in the correct ipspace with same vlans.

**Comment by kpawar-sap** [comment]
looks good to me

**Comment by chuan137** [comment]
added vlan deletion

**Review by kpawar-sap — APPROVED** [review]

**Review by Carthaca — APPROVED** [review]
Interesting, by determining the vlans that way, we take care to delete all unused vlans, which is good 👍

**Pull request merged**
